keywords = {
# Generic suspicious
    'login': 30,
    'log-in': 30,
    'sign-in': 30,
    'signin': 30,
    'account': 30,
    'verification': 30,
    'verify': 30,
    'webscr': 25,
    'password': 30,
    'credential': 25,
    'support': 30,
    'activity': 30,
    'security': 30,
    'update': 30,
    'authentication': 30,
    'authenticate': 30,
    'authorize': 30,
    'alert': 30,
    'purchase': 25,
    'transaction': 25,
    'recover': 30,
    'unlock': 30,
    'confirm': 30,
    'service': 15,
    'manage': 20,
    'invoice': 15,
    'secure': 20,
    'customer': 15,
    'client': 10,
    'bill': 10,
    'online': 10,
    'safe': 10,
    'form': 10,

# Apple iCloud
    'appleid': 70,
    'icloud': 60,
    'iforgot': 60,
    'itunes': 50,
    'apple': 35,

    'paypal': 70,

# Miscellaneous & SE tricks
    'cgi-bin': 50,
    '.com-': 20,
    '-com.': 20,
    '.net-': 20,
    '.org-': 20,
    '.com-': 20,
    '.net.': 20,
    '.org.': 20,
    '.com.': 20,
    '.gov-': 30,
    '.gov.': 30,
    '.gouv-': 40,
    '-gouv-': 40,
    '.gouv.': 40,
}

tlds = [
    '.ga',
    '.gq',
    '.ml',
    '.cf',
    '.tk',
    '.xyz'
]
